// <auto-generated />
namespace BinaShop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Product2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product2));
        
        string IMigrationMetadata.Id
        {
            get { return "201901201814219_Product2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
