// <auto-generated />
namespace BinaShop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PriceOffer1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriceOffer1));
        
        string IMigrationMetadata.Id
        {
            get { return "201901301329107_PriceOffer1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
